name: adrash
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # 
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  # 
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  nb_utils: ^7.1.3
  flex_color_scheme: ^8.1.1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.6
  loading_animation_widget: ^1.3.0
  logger: ^2.5.0
  google_maps_flutter: ^2.10.1
  # geolocator: ^13.0.2
  permission_handler: ^11.4.0
  geocoding: ^3.0.0
  geoflutterfire_plus: ^0.0.32
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  easy_stepper: ^0.8.5+1
  location: ^8.0.0
  cached_network_image: ^3.4.1
  flutter_location_search: ^2.0.0
  envied: ^1.1.1
  http: ^1.3.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  build_runner: ^2.4.15
  envied_generator: ^1.1.1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/anims/
    - assets/icon/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
    - family: Madimi
      fonts:
        - asset: assets/fonts/MadimiOne-Regular.ttf

#! native_splash
# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#2D336B"
  color_dark: "#2D336B"
  android_12:
    color: "#2D336B"
    color_dark: "#2D336B"