// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO3H5QW-UwL2kuLpNK7mbDwxe0sf57xDA',
    appId: '1:1068094623527:android:6474e14124fc1d0edae302',
    messagingSenderId: '1068094623527',
    projectId: 'adrash-6356e',
    storageBucket: 'adrash-6356e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcjcWvqx3d2iPMqeLV4sk39i5yzTfC7k',
    appId: '1:1068094623527:ios:994f7c758fb5c425dae302',
    messagingSenderId: '1068094623527',
    projectId: 'adrash-6356e',
    storageBucket: 'adrash-6356e.firebasestorage.app',
    androidClientId: '1068094623527-34jd9pndnuhtpmenk2rqv9pij4irhcja.apps.googleusercontent.com',
    iosClientId: '1068094623527-ijv8qsnpkvbvi79vbpsrqgn53kc840jc.apps.googleusercontent.com',
    iosBundleId: 'dev.abeni.adrashRider',
  );
}
